import type { Lesson, Question } from '@/types'

export const LESSONS: Lesson[] = [
  {
    id: 'lesson-1',
    number: 1,
    title: 'Lesson 1',
    subtitle: 'Introduction to Flight',
    sublessons: [
      { id: '1a', code: '1A', title: 'Lesson 1.a', label: 'Basics', hasQuiz: true },
      { id: '1b', code: '1B', title: 'Lesson 1.b', label: 'Concepts' },
      { id: '1c', code: '1C', title: 'Lesson 1.c', label: 'Review' },
    ],
  },
  {
    id: 'lesson-2',
    number: 2,
    title: 'Lesson 2',
    subtitle: 'The Four Forces of Flight',
    sublessons: [
      { id: '2a', code: '2A', title: 'Lesson 2.a', label: 'Basics' },
      { id: '2b', code: '2B', title: 'Lesson 2.b', label: 'Concepts' },
      { id: '2c', code: '2C', title: 'Lesson 2.c', label: 'Review' },
    ],
  },
  {
    id: 'lesson-3',
    number: 3,
    title: 'Lesson 3',
    subtitle: 'Aircraft Controls',
    sublessons: [
      { id: '3a', code: '3A', title: 'Lesson 3.a', label: 'Basics' },
      { id: '3b', code: '3B', title: 'Lesson 3.b', label: 'Concepts' },
      { id: '3c', code: '3C', title: 'Lesson 3.c', label: 'Review' },
    ],
  },
  {
    id: 'lesson-4',
    number: 4,
    title: 'Lesson 4',
    subtitle: 'Stability and Balance',
    sublessons: [
      { id: '4a', code: '4A', title: 'Lesson 4.a', label: 'Basics' },
      { id: '4b', code: '4B', title: 'Lesson 4.b', label: 'Concepts' },
      { id: '4c', code: '4C', title: 'Lesson 4.c', label: 'Review' },
    ],
  },
]

export const QUIZ_QUESTIONS: Question[] = [
  {
    text: 'What is the basic purpose of lift in flight?',
    options: [
      'To slow the aircraft down',
      'To support the aircraft against weight',
      'To reduce fuel consumption only',
      'To create drag during descent',
    ],
    correctIndex: 1,
    explanation: 'Lift is the upward aerodynamic force that helps oppose weight.',
  },
  {
    text: 'Which force moves an aircraft forward through the air?',
    options: ['Lift', 'Weight', 'Thrust', 'Drag'],
    correctIndex: 2,
    explanation: 'Thrust is the forward force produced by the engine or propeller.',
  },
  {
    text: 'What force acts opposite to thrust?',
    options: ['Lift', 'Drag', 'Weight', 'Balance'],
    correctIndex: 1,
    explanation: 'Drag resists forward motion and acts opposite the direction of travel.',
  },
  {
    text: 'Which force must be greater than weight for an aircraft to climb?',
    options: ['Drag', 'Lift', 'Thrust', 'Balance'],
    correctIndex: 1,
    explanation: 'An aircraft climbs when lift exceeds weight.',
  },
  {
    text: 'What is weight mainly caused by?',
    options: [
      'Gravity acting on the aircraft mass',
      'Air moving over the wings',
      'The propeller spinning',
      'The shape of the fuselage',
    ],
    correctIndex: 0,
    explanation: 'Weight is the downward force caused by gravity.',
  },
  {
    text: 'What are the four forces of flight?',
    options: [
      'Lift, weight, thrust, and drag',
      'Pitch, roll, yaw, and trim',
      'Fuel, engine, wing, and runway',
      'Aileron, elevator, rudder, and flap',
    ],
    correctIndex: 0,
    explanation: 'The four primary forces are lift, weight, thrust, and drag.',
  },
]

// Server-side registry: maps quiz_id → authoritative question list.
// The server uses this to calculate scores — the client never sends a score.
export const QUIZ_REGISTRY: Record<string, Question[]> = {
  'Lesson 1.a Quiz': QUIZ_QUESTIONS,
  'Four Forces of Flight Review': QUIZ_QUESTIONS,
}

export const SUBLESSON_CONTENT: Record<string, string> = {
  '1a': `
    <h3>Introduction to Flight</h3>
    <p>Flight is the process by which an object moves through the air. For an aircraft to fly, four forces must be in balance: lift, weight, thrust, and drag.</p>
    <div class="divider"></div>
    <h3>Key Concepts</h3>
    <div class="card note">
      <ul>
        <li><strong>Lift</strong> — the upward force generated by the wings</li>
        <li><strong>Weight</strong> — the downward force due to gravity</li>
        <li><strong>Thrust</strong> — the forward force from the engine</li>
        <li><strong>Drag</strong> — the rearward resistance force</li>
      </ul>
    </div>
  `,
  '1b': `<h3>Flight Concepts</h3><p>Understanding how the forces interact is the foundation of flight theory. When thrust exceeds drag and lift exceeds weight, the aircraft accelerates and climbs.</p>`,
  '1c': `<h3>Review: Introduction to Flight</h3><p>Review the four forces and how they affect aircraft performance in various phases of flight.</p>`,
  '2a': `<h3>The Four Forces in Detail</h3><p>Each force has a specific cause and effect on aircraft motion. Pilots learn to manipulate these forces through throttle and control surface inputs.</p>`,
}
